### ISSUE TITLE
Retrieving messages from Django

### ISSUE THREAD

**Issue by yhl48** [Decoder3-14/React-Native-Django-Chat-App#1]
Hi, I read the code in detail but had trouble understanding how messages are retrieved from the database and broadcast via Channels on the frontend, could you please clarify? 

The code here looks like the messages are manually defined without connection to the database, but I might be wrong.
https://github.com/Decoder3-14/React-Native-Django-Chat-App/blob/bd60c6c9dac9bfdb6849fed754709888549055e8/ChatApp/src/components/chat/Chat.tsx#L8

**Comment by kalideir** [comment]
@yhl48 Hi

I have not finished the project I got busy, unfortunately. The way to extract msgs from the db to the front end can be done through the consumer's file. 

Then on the frontend side, you open a WebSocket with the URL that points to that consumer and fetch the message and then pass them to the chat component.

**Comment by yhl48** [comment]
@Decoder3-14 Thank you for the reply, I will look into it. Look forward to learning from the fully implemented code!

**Comment by kalideir** [comment]
@yhl48 I will start working on react native stuff again soon, I will mention you once I finish this project.
